spring:
  cloud:
    gateway:
      routes:
        - id: bilibili_admin_admin
          uri: lb://bilibili-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: bilibili_admin_cloud
          uri: lb://bilibili-cloud
          predicates:
            - Path=/api/cloud/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}