spring:
  profiles:
    active: dev


#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  level:
    org.springframework.cloud.gateway: DEBUG #设置Gateway的日志级别为DEBUG
  file:
    path: I:\JavaSource\hilihili\logs\hilihili-gateway\ #设置输出日志文件的位置
